const assert=require('node:assert/strict');
const {Journey}=require('../source/journey.js');
const pose=(z)=>({x:3,y:1.73,z,yaw:0,stride:z,moving:1});
const journey=Journey.create(pose(2));
Journey.advance(journey,10,pose(1));
Journey.advance(journey,2,pose(-1),.5);
assert.equal(journey.worldTime,10);
assert.equal(journey.personalTime,12);
assert.equal(journey.forwardMemory,11);
assert.equal(journey.reverseMemory,1);
assert.equal(journey.direction,-1);
assert.equal(journey.segments.length,2);
assert.equal(journey.segments[0].samples.at(-1).z,0);
assert.equal(journey.segments[1].samples[0].worldTime,11);
assert.equal(Journey.atWorld(journey.segments[0],10).z,1);
assert.equal(Journey.atWorld(journey.segments[0],12),null);
Journey.advance(journey,20,pose(-3));
assert.equal(journey.worldTime,-10);
assert.equal(journey.personalTime,32);
assert.equal(journey.forwardMemory,11);
assert.equal(journey.reverseMemory,21);
assert.equal(Journey.atWorld(journey.segments[0],-10),null);
Journey.advance(journey,2,pose(3),.5);
assert.equal(journey.worldTime,-10);
assert.equal(journey.direction,1);
assert.equal(journey.personalTime,34);
const observed=Journey.atWorld(journey.segments[1],-10);
assert.equal(observed.personalTime,32);
assert.equal(observed.forwardMemory,11);
assert.equal(observed.reverseMemory,21);
Journey.advance(journey,100,pose(5));
assert.equal(journey.worldTime,90);
assert.equal(journey.personalTime,134);
assert.equal(journey.forwardMemory+journey.reverseMemory,134);
console.log('PASS: exact crossing split, continuous personal time, recorded selves, repeated reversal and unrestricted world time');
