(async () => {
'use strict';
const $=s=>document.querySelector(s), T=THREE;
await document.fonts.load('12px "Forest Sans"');
const mobile=matchMedia('(pointer:coarse)').matches, reduced=matchMedia('(prefers-reduced-motion:reduce)').matches;
if(mobile)document.body.classList.add('touch');
let seed=123829;function rnd(){seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;}
const R=(a,b)=>a+(b-a)*rnd(), clamp=(n,a=0,b=1)=>Math.max(a,Math.min(b,n)), mix=(a,b,t)=>a+(b-a)*t, smooth=(a,b,x)=>{x=clamp((x-a)/(b-a));return x*x*(3-2*x);}, TAU=Math.PI*2;
const state={t:0,observer:'a',playing:!reduced,entered:false,cinema:!reduced,personalTime:0,forwardMemory:0,reverseMemory:0,inspected:'self',crossings:0,portalArmed:true,sound:false,lookYaw:.25,lookPitch:0};
let renderer;
try{renderer=new T.WebGLRenderer({antialias:false,alpha:false,powerPreference:'high-performance'});}catch(e){$('#error').classList.add('show');return;}
renderer.setPixelRatio(Math.min(devicePixelRatio,mobile?1.2:1.65));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.NoToneMapping;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.shadowMap.autoUpdate=false;renderer.shadowMap.needsUpdate=true;
$('#world').appendChild(renderer.domElement);
const scene=new T.Scene();scene.fog=new T.FogExp2(0xc1c7ad,.0135);
const camera=new T.PerspectiveCamera(61,innerWidth/innerHeight,.08,220);camera.rotation.order='YXZ';scene.add(camera);
const clock=new T.Clock();const dummy=new T.Object3D(), color=new T.Color();const v3=(x=0,y=0,z=0)=>new T.Vector3(x,y,z);
const wind={value:state.t*46};let elapsed=0,lastUI=-1,frameCount=0,entryTime=0,cinemaTime=0,toastTimer,slowFrames=0,lastRenderSignature="";
const keys=new Set();let moveStick={x:0,y:0},drag=null,joystickId=null,footstep=0;
const sceneCounters={};
function mat(c,opts={}){return new T.MeshStandardMaterial({color:c,roughness:.88,metalness:0,flatShading:true,...opts});}
const stone=mat(0xffffff),darkstone=mat(0x697969),trunkMat=mat(0xffffff),leafMat=mat(0xffffff),mossMat=mat(0x5e733b),gold=mat(0xc5a45d,{metalness:.65,roughness:.32});
function mesh(geo,material,pos,scale,parent=scene,shadow=true){const m=new T.Mesh(geo,material);if(pos)m.position.copy(pos);if(scale)m.scale.copy(scale);m.castShadow=shadow;m.receiveShadow=true;parent.add(m);return m;}
const box=new T.BoxGeometry(1,1,1),rockGeo=new T.IcosahedronGeometry(1,1),foliageGeo=new T.IcosahedronGeometry(1,mobile?1:2),coneGeo=new T.ConeGeometry(1,1,7);
function instanced(geo,material,items,shadow=true){const m=new T.InstancedMesh(geo,material,items.length);for(let i=0;i<items.length;i++){const p=items[i];dummy.position.set(p.x||0,p.y||0,p.z||0);dummy.rotation.set(p.rx||0,p.ry||0,p.rz||0);dummy.scale.set(p.sx??p.s??1,p.sy??p.s??1,p.sz??p.s??1);dummy.updateMatrix();m.setMatrixAt(i,dummy.matrix);if(p.c!==undefined)m.setColorAt(i,color.set(p.c));}m.castShadow=shadow;m.receiveShadow=true;m.instanceMatrix.needsUpdate=true;if(m.instanceColor)m.instanceColor.needsUpdate=true;scene.add(m);return m;}
function terrain(x,z){let y=.18*Math.sin(x*.28)+.13*Math.cos(z*.31)+Math.max(0,Math.hypot(x,z)-16)*.13+Math.max(0,Math.hypot(x,z)-22)*Math.sin(x*.1+z*.08)*.10;const river=-10+Math.sin(z*.115)*2;const trough=Math.exp(-Math.pow((x-river)/2.25,4));y-=trough*1.5;const pond=Math.exp(-((x+7)*(x+7)/19+(z+1)*(z+1)/30));y-=pond*1.35;return y;}
function pathX(z){return 4+Math.sin(z*.15)*3.2;}
function grassWind(material,strength=.17){material.onBeforeCompile=shader=>{shader.uniforms.uWind=wind;shader.vertexShader='uniform float uWind;\n'+shader.vertexShader;shader.vertexShader=shader.vertexShader.replace('#include <begin_vertex>',`#include <begin_vertex>\n#ifdef USE_INSTANCING\nfloat wa=sin(uWind*1.3+instanceMatrix[3].x*.6+instanceMatrix[3].z*.37); transformed.x += wa * pow(max(position.y,0.0),2.0) * ${strength.toFixed(3)};\n#endif`);};}
// Seamless, hand-composed surface grain keeps stone and wood tactile up close.
function texture(kind){const c=document.createElement('canvas');c.width=c.height=256;const x=c.getContext('2d');x.fillStyle='#c4c0ac';x.fillRect(0,0,256,256);
 if(kind==='bark'){x.fillStyle='#adab98';x.fillRect(0,0,256,256);for(let i=0;i<180;i++){const xx=rnd()*256,w=R(.5,4);x.fillStyle=`rgba(${rnd()>.5?'235,224,185':'35,40,28'},${R(.06,.35)})`;x.fillRect(xx,0,w,256);x.beginPath();x.moveTo(xx,R(0,256));x.lineTo(xx+R(-8,8),R(0,256));x.strokeStyle='rgba(30,38,25,.23)';x.lineWidth=R(.5,2);x.stroke();}}
 else{for(let i=0;i<17000;i++){const b=Math.floor(R(75,225));x.fillStyle=`rgba(${b},${b+Math.floor(R(-7,8))},${b-10},${R(.1,.35)})`;const size=kind==='ground'?R(.5,3):R(.4,2);x.fillRect(rnd()*256,rnd()*256,size,size);}for(let i=0;i<70;i++){x.beginPath();x.ellipse(rnd()*256,rnd()*256,R(3,15),R(2,8),rnd()*TAU,0,TAU);x.fillStyle=kind==='ground'?'rgba(64,77,31,.10)':'rgba(84,103,55,.10)';x.fill();}}
 const tex=new T.CanvasTexture(c);tex.wrapS=tex.wrapT=T.RepeatWrapping;tex.colorSpace=T.SRGBColorSpace;tex.anisotropy=Math.min(4,renderer.capabilities.getMaxAnisotropy());return tex;}
const barkTex=texture('bark');trunkMat.map=barkTex;trunkMat.bumpMap=barkTex;trunkMat.bumpScale=.08;
const stoneTex=texture('stone');stone.map=stoneTex;stone.bumpMap=stoneTex;stone.bumpScale=.055;
// Atmospheric sky: the sun, cloud banks and their motion share the world's time.
const skyMat=new T.ShaderMaterial({side:T.BackSide,depthWrite:false,uniforms:{uTime:wind},vertexShader:'varying vec3 vRay;void main(){vRay=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:`varying vec3 vRay;uniform float uTime;
float hash(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453);}float noise(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(hash(i),hash(i+vec2(1,0)),f.x),mix(hash(i+vec2(0,1)),hash(i+vec2(1,1)),f.x),f.y);}float fbm(vec2 p){return .57*noise(p)+.28*noise(p*2.03)+.15*noise(p*4.13);}
void main(){vec3 r=normalize(vRay);float h=max(r.y,0.);vec3 c=mix(vec3(.86,.80,.58),vec3(.20,.42,.46),pow(h,.48));vec3 sun=normalize(vec3(-.48,.34,-.79));float sd=dot(r,sun);c+=vec3(1.,.69,.31)*pow(max(sd,0.),18.)*.65;c+=vec3(8.,5.7,2.6)*smoothstep(.99915,.9996,sd);if(r.y>.035){vec2 uv=r.xz/(r.y+.18)*1.2+vec2(uTime*.003,0.);float cl=fbm(uv*2.2);float a=smoothstep(.52,.76,cl)*smoothstep(.04,.25,r.y);c=mix(c,vec3(1.08,1.02,.81),a*.68);}gl_FragColor=vec4(c,1.);}`});
mesh(new T.SphereGeometry(180,32,18),skyMat,null,null,scene,false);
scene.add(new T.HemisphereLight(0xe6f3d0,0x53624e,1.9));
const sun=new T.DirectionalLight(0xffdf9d,3.5);sun.position.set(-23,38,-26);sun.castShadow=true;sun.shadow.mapSize.set(mobile?1024:2048,mobile?1024:2048);Object.assign(sun.shadow.camera,{left:-29,right:29,top:29,bottom:-29,near:1,far:100});sun.shadow.normalBias=.045;sun.shadow.bias=-.00015;sun.target.position.set(0,0,-2);scene.add(sun,sun.target);
const fill=new T.DirectionalLight(0xa2d6db,.55);fill.position.set(20,8,15);scene.add(fill);
// Uneven ground with an actual river bed, warm paths and moss.
const groundGeo=new T.PlaneGeometry(130,130,160,160);groundGeo.rotateX(-Math.PI/2);let a=groundGeo.attributes.position;const groundColors=[];
for(let i=0;i<a.count;i++){const x=a.getX(i),z=a.getZ(i),y=terrain(x,z);a.setY(i,y);const onPath=Math.exp(-Math.pow((x-pathX(z))/2.3,4));const n=.055*Math.sin(x*2.7+z*.6)+.045*Math.cos(z*3.1)+.035*Math.sin(x*.63+z*.77);const c=new T.Color().setRGB(.16+n+onPath*.10,.24+n-onPath*.025,.085+n*.6+onPath*.035);groundColors.push(c.r,c.g,c.b);}
groundGeo.setAttribute('color',new T.Float32BufferAttribute(groundColors,3));groundGeo.computeVertexNormals();const groundTexture=texture('ground');groundTexture.repeat.set(80,80);const groundMat=mat(0xffffff,{vertexColors:true,flatShading:false,map:groundTexture,bumpMap:groundTexture,bumpScale:.05});mesh(groundGeo,groundMat,null,null,scene,false);
// Layered mountain silhouettes hide the edge of the playable forest.
for(let layer=0;layer<3;layer++){const g=new T.PlaneGeometry(160,30,64,1);const p=g.attributes.position;for(let i=0;i<p.count;i++){const x=p.getX(i),top=p.getY(i)>0;p.setY(i,top?12+Math.sin(x*.09+layer)*7+Math.sin(x*.26+2)*3+Math.cos(x*.51)*1.7:-6);}g.computeVertexNormals();const m=mesh(g,mat([0x738e7c,0x90a695,0xa4b3a0][layer],{side:T.DoubleSide}),v3(0,0,-57-layer*17),null,scene,false);m.renderOrder=-1;}
// Stones, broken steps, ferns, flowers and thousands of wind-bent blades.
const rocks=[],pavers=[],grasses=[],ferns=[],flowerStems=[],flowerHeads=[];
for(let i=0;i<120;i++){const x=R(-28,28),z=R(-28,26),y=terrain(x,z);if(y<-.6)continue;const s=R(.2,.8);rocks.push({x,y:y+s*.25,z,sx:s,sy:s*R(.4,.85),sz:s*R(.65,1.4),ry:R(0,TAU),c:[0x89917a,0x6d7f66,0x9c9e84,0x5a7161][i%4]});}
for(let z=-5;z<23;z+=1.18){for(let j=-1;j<=1;j++){const x=pathX(z)+j*.73;pavers.push({x:x+R(-.08,.08),y:terrain(x,z)+.06,z:z+R(-.12,.12),sx:R(.64,.72),sy:R(.13,.2),sz:R(.78,.98),ry:R(-.1,.1),c:[0xb5ad8c,0x9b9e83,0xa6a689,0xc2b394][Math.floor(rnd()*4)]});}}
instanced(rockGeo,stone,rocks);
const slabShape=new T.Shape();slabShape.moveTo(-.44,-.5);slabShape.lineTo(.43,-.47);slabShape.lineTo(.5,.36);slabShape.lineTo(.32,.5);slabShape.lineTo(-.46,.44);slabShape.closePath();
const slabGeo=new T.ExtrudeGeometry(slabShape,{depth:.8,bevelEnabled:true,bevelThickness:.07,bevelSize:.06,bevelSegments:1,steps:1});slabGeo.center();slabGeo.rotateX(-Math.PI/2);
instanced(slabGeo,stone,pavers);
const bladeGeo=new T.BufferGeometry();bladeGeo.setAttribute('position',new T.Float32BufferAttribute([-.05,0,0,.05,0,0,.04,.62,0, 0,0,-.04,0,0,.04,.015,.43,.03],3));bladeGeo.computeVertexNormals();
const grassMat=mat(0xffffff,{side:T.DoubleSide});grassWind(grassMat,.20);
for(let i=0;i<(mobile?9000:17000);i++){let x=R(-35,35),z=R(-32,28);const y=terrain(x,z);if(y<-.35||Math.abs(x-pathX(z))<1.27&&z>-6||Math.hypot(x,z+4.5)<3.6)continue;const s=R(.40,1.35);grasses.push({x,y:y-.035,z,sx:s,sy:s,sz:s,ry:R(0,TAU),c:[0x8c993f,0x6f893b,0x4f723a,0xb5ad57,0x69874b][Math.floor(rnd()*5)]});}
instanced(bladeGeo,grassMat,grasses,false);
for(let i=0;i<140;i++){const x=R(-22,20),z=R(-23,21),y=terrain(x,z);if(y<-.25||Math.abs(x-pathX(z))<1.5)continue;for(let j=0;j<5;j++)ferns.push({x:x+Math.sin(j)*.08,y:y+.2,z,rx:R(-.6,.6),ry:j*1.25,rz:R(-.5,.5),sx:.6,sy:R(.5,1),sz:.6,c:i%2?0x729a48:0x486a40});if(i%3===0){flowerStems.push({x,y:y+.19,z,sx:.025,sy:.4,sz:.025,c:0x668f4d});flowerHeads.push({x,y:y+.43,z,sx:.1,sy:.06,sz:.1,c:i%2?0xebcc72:0xf1e4af});}}
instanced(bladeGeo,grassMat,ferns,false);instanced(box,grassMat,flowerStems,false);instanced(new T.IcosahedronGeometry(1,0),mat(0xffffff),flowerHeads,false);
// Tall trees are instanced: a forest, not a backdrop image.
const trunks=[],crowns=[],branches=[],treeLocations=[];const trunkGeo=new T.CylinderGeometry(.7,1,1,7,1);
function branch(from,to,radius,c=0x625342){const d=to.clone().sub(from),mid=from.clone().add(to).multiplyScalar(.5);const q=new T.Quaternion().setFromUnitVectors(v3(0,1,0),d.clone().normalize());const e=new T.Euler().setFromQuaternion(q);branches.push({x:mid.x,y:mid.y,z:mid.z,rx:e.x,ry:e.y,rz:e.z,sx:radius,sy:d.length(),sz:radius,c});}
function tree(x,z,h,s,hero=false){const y=terrain(x,z);treeLocations.push({x,z,r:hero?.95:s*.38});trunks.push({x,y:y+h*.5,z,sx:s*.57,sy:h,sz:s*.52,rz:.02,c:hero?0x64523c:0x5e5742});
 const top=y+h;const palette=hero?[0xa64a1e,0xcd7226,0xd88d32,0xe3a94b,0xc06624,0xefb957]:[0x65794a,0x809052,0xb89b42,0x9d8f36,0x688148,0xc19032];
 const n=hero?34:Math.round(R(4,8));for(let j=0;j<n;j++){const angle=j*2.4,r=hero?Math.sqrt(j/n)*4.2:R(.4,2.1)*s;const xx=x+Math.cos(angle)*r,zz=z+Math.sin(angle)*r*.8,yy=top+Math.sin(j*1.7)*s*.6+(hero?1.6:0);const k=hero?R(1.5,2.6):R(1.5,2.4)*s;crowns.push({x:xx,y:yy,z:zz,sx:k,sy:k*.68,sz:k*.85,ry:R(0,TAU),c:palette[j%palette.length]});if(hero&&j%3===0)branch(v3(x,top-3,z),v3(xx,yy-.6,zz),.17+R(0,.12),0x68523b);else if(!hero&&j<3)branch(v3(x,top-h*.4,z),v3(xx,yy-.7,zz),s*.15,0x6b6047);}
}
for(let i=0;i<82;i++){const angle=R(0,TAU),r=R(14,48),x=Math.cos(angle)*r,z=Math.sin(angle)*r-4;if(z>10&&Math.abs(x)<10||Math.hypot(x-4,z-12)<4.5)continue;if(terrain(x,z)<-.3)continue;tree(x,z,R(6.5,11),R(.8,1.5));}
tree(5,-7,8,1.75,true);tree(-14,8,10,1.6);tree(16,9,11,1.5);
instanced(trunkGeo,trunkMat,trunks);instanced(trunkGeo,trunkMat,branches);const crownMesh=instanced(foliageGeo,leafMat,crowns);
const canopyDetail=[];for(let i=0;i<240;i++){const a=R(0,TAU),r=R(1,5),x=5+Math.cos(a)*r,z=-7+Math.sin(a)*r*.78,y=8.8+R(-1.3,2.2);canopyDetail.push({x,y,z,sx:R(.25,.6),sy:R(.2,.5),sz:R(.3,.65),ry:R(0,TAU),c:[0xe7b34b,0xd5872d,0xb96926,0xdca442][i%4]});}instanced(foliageGeo,leafMat,canopyDetail);
// Roots wrap the base of the central tree.
const rootItems=[];for(let i=0;i<10;i++){const angle=i/10*TAU,x=5+Math.cos(angle)*1.2,z=-7+Math.sin(angle)*1.2;rootItems.push({x,y:terrain(x,z)+.17,z,sx:1.7,sy:.21,sz:.23,ry:-angle,c:0x65543b});}instanced(rockGeo,trunkMat,rootItems);
// A raised rock wall and an emerald waterfall.
const cliff=[];for(let i=0;i<38;i++){const x=-12+R(-3.1,2.6),z=-17+R(-2,1.5),h=R(1.7,5.4);cliff.push({x,y:h*.45,z,sx:R(1.2,2.3),sy:h*.7,sz:R(.8,1.6),ry:R(-.3,.3),c:[0x879887,0x677f71,0x9caa92][i%3]});}instanced(rockGeo,stone,cliff);
const waterUniforms={uTime:wind,uEye:{value:camera.position},uColor:{value:new T.Color(0x247b73)}};
const waterMat=new T.ShaderMaterial({transparent:true,depthWrite:false,side:T.DoubleSide,uniforms:waterUniforms,vertexShader:`varying vec3 vPos;uniform float uTime;void main(){vec3 p=position;p.y+=sin(p.x*2.1+p.z*1.6+uTime*1.7)*.025;vPos=(modelMatrix*vec4(p,1.)).xyz;gl_Position=projectionMatrix*viewMatrix*vec4(vPos,1.);}`,fragmentShader:`varying vec3 vPos;uniform float uTime;uniform vec3 uEye;uniform vec3 uColor;
void main(){vec2 p=vPos.xz;float w=sin(p.x*5.+p.y*2.+uTime*3.)*.5+sin(p.y*8.-uTime*2.+sin(p.x*2.))*.35;float fine=sin(p.x*22.+sin(p.y*12.-uTime*3.))*sin(p.y*21.+uTime*4.);vec3 n=normalize(vec3(w*.1,1.,cos(p.y*4.-uTime)*.13));vec3 v=normalize(uEye-vPos);float f=pow(1.-max(dot(v,n),0.),3.);vec3 c=mix(uColor,vec3(.62,.80,.70),f*.7);c+=pow(max(fine,0.),16.)*vec3(.4,.59,.45)*.5;c+=smoothstep(.90,1.0,w)*.09;gl_FragColor=vec4(c,.89);}`});
const waterVerts=[],waterIdx=[];for(let i=0;i<=100;i++){const z=-37+i*.62,x=-10+Math.sin(z*.115)*2;for(let j=0;j<2;j++)waterVerts.push(x+(j?1.9:-1.9),-.37,z);if(i<100){const k=i*2;waterIdx.push(k,k+1,k+2,k+1,k+3,k+2);}}
const riverGeo=new T.BufferGeometry();riverGeo.setAttribute('position',new T.Float32BufferAttribute(waterVerts,3));riverGeo.setIndex(waterIdx);riverGeo.computeVertexNormals();mesh(riverGeo,waterMat,null,null,scene,false);
const pondGeo=new T.CircleGeometry(1,64);pondGeo.rotateX(-Math.PI/2);mesh(pondGeo,waterMat,v3(-7,-.37,-1),v3(4.3,1,5.3),scene,false);
const fallsMat=new T.ShaderMaterial({transparent:true,side:T.DoubleSide,depthWrite:false,uniforms:{uTime:wind},vertexShader:'varying vec2 vUv;void main(){vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:`varying vec2 vUv;uniform float uTime;void main(){float bands=sin(vUv.x*64.+sin(vUv.y*9.+uTime*4.))*0.5+0.5;float flow=sin(vUv.y*45.+uTime*12.+vUv.x*15.)*.5+.5;float edge=smoothstep(0.,.12,vUv.x)*smoothstep(1.,.88,vUv.x);gl_FragColor=vec4(mix(vec3(.3,.72,.68),vec3(.88,1.,.92),bands*.6+flow*.2),edge*(.22+bands*.3));}`});
mesh(new T.PlaneGeometry(1.75,5.3,6,12),fallsMat,v3(-11.2,2.32,-15.1),null,scene,false);
const sprayCount=mobile?220:400,spray=new T.InstancedMesh(new T.IcosahedronGeometry(.04,0),mat(0xb2f4dc,{emissive:0x347e65,emissiveIntensity:.3,roughness:.2}),sprayCount);spray.frustumCulled=false;scene.add(spray);const drops=Array.from({length:sprayCount},()=>({phase:rnd(),x:R(-.78,.78),z:R(-.3,.5),scale:R(.5,1.8)}));
const rippleMat=new T.MeshBasicMaterial({color:0xc9edda,transparent:true,opacity:.2,side:T.DoubleSide,depthWrite:false});const ripples=[];for(let i=0;i<7;i++){const r=mesh(new T.RingGeometry(.95,1,48),rippleMat.clone(),v3(-11.2,-.32,-14.8),null,scene,false);r.rotation.x=-Math.PI/2;ripples.push(r);}
// A circular monument: every stone has a reversible, continuous trajectory.
const gate=new T.Group();scene.add(gate);const blocks=[];
for(let i=0;i<24;i++){const angle=i/24*TAU;const target=v3(Math.cos(angle)*2.8,3.2+Math.sin(angle)*2.8,-4.5);const block=mesh(box,mat(i%3===0?0xb4b399:0xa2a489,{map:stoneTex,bumpMap:stoneTex,bumpScale:.07}),target.clone(),v3(.74,.81,.9),gate);block.rotation.z=angle;const end=v3(target.x*1.15+R(-2.1,2.1),.35+R(0,.2),-4.5+R(-3.2,4.3));end.y=Math.max(.3,terrain(end.x,end.z)+.4);blocks.push({mesh:block,target,end,angle,spin:v3(R(-2,2),R(-2,2),R(-2,2))});
 const mark=mesh(new T.BoxGeometry(.045,.29,.013),gold,v3(0,0,.508),null,block,false);mark.rotation.z=i%3*.6;}
// The visible monument uses two draws; the lightweight objects above retain its poses.
const gateStones=new T.InstancedMesh(box,blocks[0].mesh.material,blocks.length),gateMarks=new T.InstancedMesh(new T.BoxGeometry(.045,.29,.013),gold,blocks.length);gateStones.castShadow=true;gateStones.receiveShadow=true;gateStones.frustumCulled=false;gateMarks.frustumCulled=false;gate.visible=false;scene.add(gateStones,gateMarks);const markMatrix=new T.Matrix4();
const gateBase=[];for(let side of [-1,1])for(let i=0;i<3;i++)gateBase.push({x:side*2.55,y:.17+i*.12,z:-4.5,sx:1.75-i*.2,sy:.24,sz:1.9-i*.18,c:0x929b7d});instanced(box,stone,gateBase);
const ruinExtras=[];for(let i=0;i<14;i++){const x=R(-4.8,5),z=R(-8,-2);ruinExtras.push({x,y:terrain(x,z)+.18,z,sx:R(.2,.65),sy:R(.2,.4),sz:R(.2,.65),ry:R(0,TAU),c:0x8b987c});}instanced(rockGeo,stone,ruinExtras);
// A near-field handful of leaves makes the reversal unmistakable.
const leafGeo=new T.BufferGeometry();
const outline=[[0,.32],[.04,.20],[.11,.24],[.09,.14],[.18,.14],[.11,.07],[.14,.035],[.025,.015],[.008,-.065],[-.008,-.065],[-.025,.015],[-.14,.035],[-.11,.07],[-.18,.14],[-.09,.14],[-.11,.24],[-.04,.20]],leafVertices=[],leafColors=[];
for(let i=0;i<outline.length;i++){const a=outline[i],b=outline[(i+1)%outline.length];leafVertices.push(0,.11,.023,a[0],a[1],0,b[0],b[1],0);leafColors.push(1,1,.9,.76,.84,.7,.85,.88,.75);}
leafGeo.setAttribute('position',new T.Float32BufferAttribute(leafVertices,3));leafGeo.setAttribute('color',new T.Float32BufferAttribute(leafColors,3));leafGeo.computeVertexNormals();
const leafCount=mobile?230:430;const fallingLeaves=new T.InstancedMesh(leafGeo,mat(0xffffff,{side:T.DoubleSide,vertexColors:true}),leafCount);fallingLeaves.instanceMatrix.setUsage(T.DynamicDrawUsage);fallingLeaves.castShadow=false;fallingLeaves.frustumCulled=false;scene.add(fallingLeaves);
const leafData=[];for(let i=0;i<leafCount;i++){const theta=R(0,TAU),r=R(.8,4.4),start=v3(5+Math.cos(theta)*r,8.8+R(-.6,2.1),-7+Math.sin(theta)*r*.8);let end=v3(R(-9,15),.1,R(-3,20));end.y=terrain(end.x,end.z)+.06;leafData.push({start,end,phase:R(0,TAU),spin:R(-8,8),s:R(.4,.95),delay:R(0,.2)});fallingLeaves.setColorAt(i,color.set([0xe7b650,0xd98931,0xb95823,0xe5cf73,0xdca03e][i%5]));}
// Fallen flowers and loose paper ride the same wind, all deterministically.
const motesGeo=new T.BufferGeometry(),motePositions=new Float32Array(160*3);motesGeo.setAttribute('position',new T.BufferAttribute(motePositions,3));const moteData=Array.from({length:160},()=>({x:R(-18,18),y:R(.5,9),z:R(-18,20),phase:R(0,TAU)}));
const moteTexCanvas=document.createElement('canvas');moteTexCanvas.width=moteTexCanvas.height=32;const mx=moteTexCanvas.getContext('2d'),mg=mx.createRadialGradient(16,16,0,16,16,16);mg.addColorStop(0,'#fff3bd');mg.addColorStop(.18,'#ffdf8ba0');mg.addColorStop(1,'#ffdf8b00');mx.fillStyle=mg;mx.fillRect(0,0,32,32);const motes=new T.Points(motesGeo,new T.PointsMaterial({size:.1,map:new T.CanvasTexture(moteTexCanvas),transparent:true,opacity:.7,depthWrite:false,blending:T.AdditiveBlending,color:0xffe8a3}));scene.add(motes);
// Birds can be followed through the trees in either direction.
const birds=[];const birdMat=mat(0xe9dcc0,{side:T.DoubleSide});const wingGeo=new T.BufferGeometry();wingGeo.setAttribute('position',new T.Float32BufferAttribute([0,0,0,.65,.06,-.13,.12,0,.23],3));wingGeo.computeVertexNormals();for(let i=0;i<5;i++){const g=new T.Group(),left=mesh(wingGeo,birdMat,null,null,g),right=mesh(wingGeo,birdMat,null,v3(-1,1,1),g);mesh(new T.ConeGeometry(.045,.29,5),birdMat,v3(0,0,.04),null,g);scene.add(g);birds.push({g,left,right,phase:i*.91});}
// Sun shafts are spatial volumes: they shift as the viewer walks past.
const shaftMat=new T.ShaderMaterial({transparent:true,depthWrite:false,side:T.DoubleSide,blending:T.AdditiveBlending,uniforms:{uTime:wind},vertexShader:'varying vec2 vUv;void main(){vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:'varying vec2 vUv;uniform float uTime;void main(){float a=pow(sin(vUv.x*3.14159),3.)*sin(vUv.y*3.14159)*.044;gl_FragColor=vec4(1.,.85,.46,a);}' });
for(let i=0;i<7;i++){const shaft=mesh(new T.PlaneGeometry(R(.5,1.4),22),shaftMat,v3(-8+i*3,8,-11+R(-3,4)),null,scene,false);shaft.rotation.z=-.48;shaft.rotation.y=.4;}
// The watch belongs to B. Its hands and three memory stones follow B's life.
const hands=new T.Group();camera.add(hands);hands.position.set(.38,-.36,-.69);hands.rotation.set(-.05,-.12,-.22);const cloth=mat(0x776c47,{roughness:1}),glove=mat(0x3d4b3c),skin=mat(0xac8862);
const sleeve=mesh(new T.CylinderGeometry(.058,.10,.38,8),cloth,v3(.045,-.20,-.015),null,hands);sleeve.rotation.z=-.1;
mesh(new T.BoxGeometry(.12,.055,.075),glove,v3(0,-.035,0),null,hands);const wrist=mesh(new T.CylinderGeometry(.053,.05,.14,8),skin,v3(0,.025,-.006),null,hands);wrist.rotation.x=.25;
const palm=mesh(new T.SphereGeometry(.066,8,6),glove,v3(0,.105,-.015),v3(.9,1.2,.65),hands);for(let i=0;i<4;i++){const finger=mesh(new T.CapsuleGeometry(.013,.055,2,5),glove,v3(-.037+i*.025,.157,-.022),null,hands);finger.rotation.x=-.6;}
const watchGroup=new T.Group();watchGroup.position.set(0,.012,.053);hands.add(watchGroup);mesh(new T.CylinderGeometry(.082,.082,.025,32),gold,null,null,watchGroup).rotation.x=Math.PI/2;const face=mesh(new T.CircleGeometry(.073,32),mat(0x153d36,{roughness:.35,metalness:.25}),v3(0,0,.014),null,watchGroup,false);
const ticks=[];for(let i=0;i<12;i++){const ang=i/12*TAU;const m=mesh(box,gold,v3(Math.sin(ang)*.063,Math.cos(ang)*.063,.017),v3(.003,i%3===0?.01:.005,.002),watchGroup,false);m.rotation.z=-ang;ticks.push(m);}
const tickInstances=new T.InstancedMesh(box,gold,12);for(let i=0;i<12;i++){ticks[i].updateMatrix();tickInstances.setMatrixAt(i,ticks[i].matrix);ticks[i].visible=false;}watchGroup.add(tickInstances);
const clockHand=new T.Group();watchGroup.add(clockHand);mesh(box,mat(0xffe6a8,{emissive:0x94672c,emissiveIntensity:.4}),v3(0,.025,.021),v3(.004,.05,.003),clockHand,false);const hourHand=new T.Group();watchGroup.add(hourHand);mesh(box,gold,v3(0,.015,.023),v3(.006,.03,.003),hourHand,false);mesh(new T.SphereGeometry(.005,8,4),gold,v3(0,0,.026),null,watchGroup,false);
const memories=[];for(let i=0;i<3;i++){const m=mesh(new T.SphereGeometry(.006,8,6),mat(0x344e42,{emissive:0x89ffdc,emissiveIntensity:0}),v3((i-1)*.019,-.096,.055),null,hands,false);memories.push(m);}
const watchLight=new T.PointLight(0xd7ffd2,.1,.6);watchLight.position.set(0,0,.1);hands.add(watchLight);
hands.traverse(o=>{if(o.isMesh)o.castShadow=false;});
// Filmlike image pipeline: soft bloom, a light grain, vignette and restrained time distortion.
const rtOptions={type:renderer.capabilities.isWebGL2?T.HalfFloatType:T.UnsignedByteType,minFilter:T.LinearFilter,magFilter:T.LinearFilter,depthBuffer:true};let mainTarget=new T.WebGLRenderTarget(1,1,rtOptions),blurA=new T.WebGLRenderTarget(1,1,{...rtOptions,depthBuffer:false}),blurB=new T.WebGLRenderTarget(1,1,{...rtOptions,depthBuffer:false});
const postScene=new T.Scene(),postCamera=new T.OrthographicCamera(-1,1,1,-1,0,1),quad=new T.Mesh(new T.PlaneGeometry(2,2));postScene.add(quad);const postVert='varying vec2 vUv;void main(){vUv=uv;gl_Position=vec4(position.xy,0.,1.);}';
const blurMat=new T.ShaderMaterial({depthTest:false,depthWrite:false,uniforms:{uMap:{value:null},uDelta:{value:new T.Vector2()},uThreshold:{value:1}},vertexShader:postVert,fragmentShader:`varying vec2 vUv;uniform sampler2D uMap;uniform vec2 uDelta;uniform float uThreshold;vec3 sampleColor(vec2 uv){vec3 c=texture2D(uMap,uv).rgb;if(uThreshold>.5){float l=max(max(c.r,c.g),c.b);c*=smoothstep(.8,2.6,l);}return c;}void main(){vec3 c=sampleColor(vUv)*.227027;c+=sampleColor(vUv+uDelta*1.384615)*.316216;c+=sampleColor(vUv-uDelta*1.384615)*.316216;c+=sampleColor(vUv+uDelta*3.230769)*.070270;c+=sampleColor(vUv-uDelta*3.230769)*.070270;gl_FragColor=vec4(c,1.);}`});
const postMat=new T.ShaderMaterial({depthTest:false,depthWrite:false,uniforms:{uMap:{value:mainTarget.texture},uBloom:{value:blurB.texture},uTime:{value:0},uReverse:{value:0},uSize:{value:new T.Vector2(1,1)},uFade:{value:0}},vertexShader:postVert,fragmentShader:`varying vec2 vUv;uniform sampler2D uMap,uBloom;uniform float uTime,uReverse,uFade;uniform vec2 uSize;
vec3 aces(vec3 x){return clamp((x*(2.51*x+.03))/(x*(2.43*x+.59)+.14),0.,1.);}void main(){vec2 uv=vUv;vec2 p=uv-.5;float edge=dot(p,p);vec2 shift=p*edge*.006*uReverse;vec3 c=texture2D(uMap,uv).rgb;c.r=texture2D(uMap,uv+shift).r;c.b=texture2D(uMap,uv-shift).b;c+=texture2D(uBloom,uv).rgb*.15;c=aces(c*1.04);c=pow(c,vec3(1./2.2));c*=1.-edge*.40;float noise=fract(sin(dot(uv*uSize,vec2(12.9898,78.233))+uTime)*43758.5453)-.5;c+=noise*.014;c=mix(c,c*vec3(.94,1.015,1.015),uReverse*.25);c*=uFade;gl_FragColor=vec4(c,1.);}`});
function resize(){const w=innerWidth,h=innerHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();const dpr=renderer.getPixelRatio();mainTarget.setSize(Math.floor(w*dpr),Math.floor(h*dpr));blurA.setSize(Math.floor(w*dpr*.3),Math.floor(h*dpr*.3));blurB.setSize(Math.floor(w*dpr*.3),Math.floor(h*dpr*.3));postMat.uniforms.uSize.value.set(w*dpr,h*dpr);hands.position.set(mobile?.14:.42,mobile?-.27:-.27,-.82);hands.scale.setScalar(mobile?.62:.78);}
addEventListener('resize',resize);resize();
// Cinematic path can be left at any instant by moving or dragging.
// __EXPERIENCE__
const cameraPath=new T.CatmullRomCurve3([v3(4.4,2.1,12),v3(5.7,2.1,9),v3(6.4,2.1,6.5),v3(5.5,2.1,3),v3(3,2.1,1.2),v3(3,2.1,-1.8)],false,'catmullrom',.3);
camera.position.copy(cameraPath.getPointAt(0));camera.lookAt(0,3,-4);state.lookYaw=camera.rotation.y;state.lookPitch=camera.rotation.x;previousPortalPosition.copy(camera.position);
function leaveCinema(){if(!state.cinema)return;state.cinema=false;$('#cinema').setAttribute('aria-pressed','false');state.lookYaw=camera.rotation.y;state.lookPitch=camera.rotation.x;}
function notify(text){$('#toast').textContent=text;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),2300);}
function updateButtons(){
 $('#play').setAttribute('aria-label',state.playing?'일시 정지':'재생');
 $('#play').innerHTML=state.playing?'<svg viewBox="0 0 24 24"><path d="M8 5v14M16 5v14" stroke-width="2.5"/></svg>':'<svg viewBox="0 0 24 24"><path d="m8 5 10 7-10 7Z" fill="currentColor" stroke="none"/></svg>';
 $('#observer').textContent=state.observer==='b'?'역방향':'순방향';$('#arrow').textContent=state.observer==='b'?'←':'→';
 document.body.classList.toggle('reversing',state.observer==='b');$('#cinema').setAttribute('aria-pressed',String(state.cinema));
}
function crossPortal(){state.observer=state.observer==='b'?'a':'b';state.crossings++;state.portalArmed=false;$('#flash').classList.add('on');setTimeout(()=>$('#flash').classList.remove('on'),180);notify('포탈 통과 · 이전 기억은 유지됩니다');updateButtons();}
function play(){state.playing=!state.playing;updateButtons();}
function enter(){if(state.entered)return;state.entered=true;entryTime=elapsed;document.body.classList.add('entered');$('#cover').classList.add('dismissed');$('#instructions').classList.add('show');setTimeout(()=>$('#instructions').classList.remove('show'),14000);state.playing=!reduced;if(!reduced)toggleSound();updateButtons();}
function restartJourney(){Object.assign(state,{t:0,observer:'a',personalTime:0,forwardMemory:0,reverseMemory:0,crossings:0,portalArmed:true,playing:!reduced,cinema:!reduced});cinemaTime=0;camera.position.copy(cameraPath.getPointAt(0));camera.lookAt(2,1.1,5);state.lookYaw=camera.rotation.y;state.lookPitch=camera.rotation.x;previousPortalPosition.copy(camera.position);updateButtons();updateWorld();updateNeurons();notify('새 여정 · 순방향에서 시작');}
$('#enter').addEventListener('click',enter);$('#play').addEventListener('click',play);$('#restart').addEventListener('click',restartJourney);
$('#cinema').addEventListener('click',()=>{if(state.cinema)leaveCinema();else{state.cinema=true;cinemaTime=0;updateButtons();}});
$('#fullscreen').addEventListener('click',async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{notify('전체 화면을 지원하지 않습니다');}});
addEventListener('keydown',e=>{if(['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName))return;if(!state.entered){if(e.code==='Enter')enter();return;}if(['KeyW','KeyA','KeyS','KeyD','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','ShiftLeft'].includes(e.code)){e.preventDefault();keys.add(e.code);leaveCinema();}if(e.code==='KeyP'&&!e.repeat)play();if(e.code==='Escape')drag=null;});
addEventListener('keyup',e=>keys.delete(e.code));
function clearInputs(){keys.clear();drag=null;moveStick={x:0,y:0};joystickId=null;$('#stick').style.transform='';}addEventListener('blur',clearInputs);document.addEventListener('visibilitychange',()=>{if(document.hidden)clearInputs();clock.getDelta();});
renderer.domElement.addEventListener('pointerdown',e=>{if(!state.entered)return;drag={id:e.pointerId,x:e.clientX,y:e.clientY,startX:e.clientX,startY:e.clientY,moved:false};renderer.domElement.setPointerCapture(e.pointerId);});
renderer.domElement.addEventListener('pointermove',e=>{if(!drag||e.pointerId!==drag.id)return;if(Math.hypot(e.clientX-drag.startX,e.clientY-drag.startY)>6)drag.moved=true;if(drag.moved){leaveCinema();state.lookYaw-=(e.clientX-drag.x)*.003;state.lookPitch=clamp(state.lookPitch-(e.clientY-drag.y)*.003,-1.25,1.2);}drag.x=e.clientX;drag.y=e.clientY;});
renderer.domElement.addEventListener('pointerup',e=>{if(drag?.id===e.pointerId){if(!drag.moved)pickRunner(e);drag=null;}});
for(const ev of ['pointercancel','lostpointercapture'])renderer.domElement.addEventListener(ev,e=>{if(drag?.id===e.pointerId)drag=null;});
const joystick=$('#joystick');function stickMove(e){const r=joystick.getBoundingClientRect(),max=r.width*.33;let x=(e.clientX-r.left-r.width*.5)/max,y=(e.clientY-r.top-r.height*.5)/max;const l=Math.hypot(x,y);if(l>1){x/=l;y/=l;}moveStick={x,y};$('#stick').style.transform=`translate(${x*max}px,${y*max}px)`;}
joystick.addEventListener('pointerdown',e=>{leaveCinema();joystickId=e.pointerId;joystick.setPointerCapture(e.pointerId);stickMove(e);});joystick.addEventListener('pointermove',e=>{if(e.pointerId===joystickId)stickMove(e);});for(const ev of ['pointerup','pointercancel','lostpointercapture'])joystick.addEventListener(ev,e=>{if(e.pointerId===joystickId){joystickId=null;moveStick={x:0,y:0};$('#stick').style.transform='';}});
// Optional procedural field recording: wind, water and very distant birds.
let audioCtx=null,master=null,windFilter=null,waterFilter=null,nextBird=0;
async function toggleSound(){try{if(!audioCtx){audioCtx=new (window.AudioContext||window.webkitAudioContext)();master=audioCtx.createGain();master.gain.value=0;master.connect(audioCtx.destination);const buffer=audioCtx.createBuffer(1,audioCtx.sampleRate*3,audioCtx.sampleRate);const data=buffer.getChannelData(0);let b=0;for(let i=0;i<data.length;i++){b=(b+(Math.random()*2-1)*.02)/1.02;data[i]=b*3.5;}const src=audioCtx.createBufferSource();src.buffer=buffer;src.loop=true;windFilter=audioCtx.createBiquadFilter();windFilter.type='lowpass';windFilter.frequency.value=600;const gain=audioCtx.createGain();gain.gain.value=.28;src.connect(windFilter).connect(gain).connect(master);src.start();const water=audioCtx.createBufferSource();water.buffer=buffer;water.loop=true;waterFilter=audioCtx.createBiquadFilter();waterFilter.type='bandpass';waterFilter.frequency.value=1700;waterFilter.Q.value=.6;const waterGain=audioCtx.createGain();waterGain.gain.value=.25;water.connect(waterFilter).connect(waterGain).connect(master);water.start();}await audioCtx.resume();state.sound=!state.sound;master.gain.setTargetAtTime(state.sound?.6:0,audioCtx.currentTime,.4);$('#sound').setAttribute('aria-pressed',String(state.sound));$('#sound').setAttribute('aria-label',state.sound?'소리 끄기':'소리 켜기');$('#sound').innerHTML=state.sound?'<svg viewBox="0 0 24 24"><path d="m10 5-5 4H2v6h3l5 4zM15 8q5 4 0 8M18 4q9 8 0 16"/></svg>':'<svg viewBox="0 0 24 24"><path d="m10 5-5 4H2v6h3l5 4zM15 9l6 6m0-6-6 6"/></svg>';}catch{notify('소리를 재생할 수 없습니다');}}
$('#sound').addEventListener('click',toggleSound);
function birdsong(){if(!audioCtx||!state.sound)return;const now=audioCtx.currentTime,osc=audioCtx.createOscillator(),g=audioCtx.createGain();osc.type='sine';osc.frequency.setValueAtTime(2100,now);osc.frequency.exponentialRampToValueAtTime(state.observer==='b'?3800:1400,now+.12);g.gain.setValueAtTime(0,now);g.gain.linearRampToValueAtTime(.013,now+.025);g.gain.exponentialRampToValueAtTime(.0001,now+.28);osc.connect(g).connect(master);osc.start();osc.stop(now+.3);osc.onended=()=>{osc.disconnect();g.disconnect();};}
function updateWorld(){
 const t=state.t;wind.value=t*46;
 const assembly=smooth(.12,.88,t);
 for(let i=0;i<blocks.length;i++){const b=blocks[i],q=smooth(.015+i*.006,.7+i*.011,assembly);b.mesh.position.lerpVectors(b.target,b.end,q);b.mesh.position.y+=Math.sin(q*Math.PI)*(1.25+(i%3)*.3);b.mesh.rotation.set(b.spin.x*q,b.spin.y*q,b.angle+b.spin.z*q);b.mesh.updateMatrix();gateStones.setMatrixAt(i,b.mesh.matrix);b.mesh.children[0].updateMatrix();markMatrix.multiplyMatrices(b.mesh.matrix,b.mesh.children[0].matrix);gateMarks.setMatrixAt(i,markMatrix);}gateStones.instanceMatrix.needsUpdate=true;gateMarks.instanceMatrix.needsUpdate=true;
 for(let i=0;i<leafCount;i++){const p=leafData[i],q=smooth(p.delay,1,t),lift=Math.sin(q*Math.PI),x=mix(p.start.x,p.end.x,q)+Math.sin(q*8+p.phase)*lift*2.1,z=mix(p.start.z,p.end.z,q)+Math.cos(q*7+p.phase)*lift*2.2,y=mix(p.start.y,p.end.y,q)+lift*Math.sin(p.phase)*.9;dummy.position.set(x,y,z);dummy.rotation.set(q*p.spin+Math.sin(t*12+p.phase)*q*.7,p.phase+q*9,q*p.spin*.7);dummy.scale.setScalar(p.s);dummy.updateMatrix();fallingLeaves.setMatrixAt(i,dummy.matrix);}fallingLeaves.instanceMatrix.needsUpdate=true;
 for(let i=0;i<sprayCount;i++){const p=drops[i],q=(t*7+p.phase)%1;dummy.position.set(-11.2+p.x*(.6+q*.7),4.94-q*q*5.25,-15.1+p.z+Math.sin(q*5+p.phase)*q*.2);dummy.rotation.set(0,0,0);dummy.scale.set(p.scale*.7,p.scale*(1+q*2),p.scale*.7);dummy.updateMatrix();spray.setMatrixAt(i,dummy.matrix);}spray.instanceMatrix.needsUpdate=true;
 for(let i=0;i<ripples.length;i++){const q=(t*8+i/ripples.length)%1;const s=.2+q*1.3;ripples[i].scale.set(s,s,1);ripples[i].material.opacity=(1-q)*.2;}
 for(let i=0;i<moteData.length;i++){const p=moteData[i];motePositions[i*3]=p.x+Math.sin(t*13+p.phase)*1.6;motePositions[i*3+1]=p.y+Math.cos(t*7+p.phase)*.4;motePositions[i*3+2]=p.z+Math.sin(t*9+p.phase)*2;}motesGeo.attributes.position.needsUpdate=true;
 for(const b of birds){const a=t*TAU*1.3+b.phase;b.g.position.set(Math.sin(a)*10,5.5+Math.sin(a*1.7)*.7,-6+Math.cos(a)*8);b.g.rotation.y=a+Math.PI*.5;const flap=Math.sin(t*160+b.phase)*.65;b.left.rotation.z=flap;b.right.rotation.z=-flap;}
 clockHand.rotation.z=-state.personalTime/48*TAU*5;hourHand.rotation.z=-state.personalTime/48*TAU*.65;for(let i=0;i<3;i++){const on=state.personalTime>[3,10,20][i];memories[i].material.emissiveIntensity=on?2.5:.03;memories[i].material.color.setHex(on?0xc8ffe4:0x344e42);}
 updateRunner();const ui=Math.round(t*1000);if(ui!==lastUI){$('#time').value=ui;$('#time').setAttribute('aria-valuetext',`${(t*48).toFixed(1)}초`);$('#time-caption').textContent=`A의 시간좌표 · ${(t*48).toFixed(1)}초`;lastUI=ui;}
}
function updateCamera(dt,realDt=dt){
 if(!state.entered){camera.position.copy(cameraPath.getPointAt(0));camera.lookAt(0,3.3,-5);hands.visible=false;return;}
 hands.visible=true;
 if(state.cinema){cinemaTime+=realDt;const q=clamp(cinemaTime/26);const wanted=cameraPath.getPointAt(q);camera.position.copy(wanted);const target=cinemaTime<19?v3(runner.position.x,1.1,5):v3(3,1.6,0);if(cinemaTime>27)target.set(runner.position.x,.9,5);const targetQ=new T.Quaternion();const m=new T.Matrix4().lookAt(camera.position,target,v3(0,1,0));targetQ.setFromRotationMatrix(m);camera.quaternion.slerp(targetQ,1-Math.exp(-realDt*3));state.lookYaw=camera.rotation.y;state.lookPitch=camera.rotation.x;
 }else{camera.rotation.set(state.lookPitch,state.lookYaw,0);let forward=(keys.has('KeyW')||keys.has('ArrowUp')?1:0)-(keys.has('KeyS')||keys.has('ArrowDown')?1:0)-moveStick.y;let side=(keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0)+moveStick.x;const length=Math.hypot(forward,side);if(length>1){forward/=length;side/=length;}const speed=keys.has('ShiftLeft')?4.7:2.9,dx=(-Math.sin(state.lookYaw)*forward+Math.cos(state.lookYaw)*side)*dt*speed,dz=(-Math.cos(state.lookYaw)*forward-Math.sin(state.lookYaw)*side)*dt*speed;
 let x=clamp(camera.position.x+dx,-23,23),z=clamp(camera.position.z+dz,-23,23);for(const tr of treeLocations){const d=Math.hypot(x-tr.x,z-tr.z);if(d<tr.r+.3){const a=Math.atan2(z-tr.z,x-tr.x);x=tr.x+Math.cos(a)*(tr.r+.3);z=tr.z+Math.sin(a)*(tr.r+.3);}}
 if(terrain(x,z)<-.55){x=camera.position.x;z=camera.position.z;}
 camera.position.x=x;camera.position.z=z;footstep+=Math.min(1,length)*dt*8;const targetY=terrain(x,z)+1.73+(reduced?0:Math.sin(footstep)*.025*Math.min(1,length));camera.position.y=mix(camera.position.y,targetY,1-Math.exp(-dt*6));
 }
 const breathe=reduced?0:Math.sin(state.personalTime*1.5)*.003;hands.position.y=-.27+breathe;hands.rotation.z=-.22+(reduced?0:Math.sin(footstep)*.015);hands.rotation.x=-.05+(reduced?0:Math.cos(footstep*.5)*.012);
}
function draw(){
 renderer.setRenderTarget(mainTarget);renderer.render(scene,camera);sceneCounters.calls=renderer.info.render.calls;sceneCounters.triangles=renderer.info.render.triangles;
 quad.material=blurMat;blurMat.uniforms.uMap.value=mainTarget.texture;blurMat.uniforms.uDelta.value.set(1/blurA.width,0);blurMat.uniforms.uThreshold.value=1;renderer.setRenderTarget(blurA);renderer.render(postScene,postCamera);
 blurMat.uniforms.uMap.value=blurA.texture;blurMat.uniforms.uDelta.value.set(0,1/blurB.height);blurMat.uniforms.uThreshold.value=0;renderer.setRenderTarget(blurB);renderer.render(postScene,postCamera);
 quad.material=postMat;renderer.setRenderTarget(null);renderer.render(postScene,postCamera);
}
function animate(){requestAnimationFrame(animate);const raw=Math.min(clock.getDelta(),1);const dt=Math.min(raw,.08);if(document.hidden)return;elapsed+=raw;
 if(state.entered&&state.playing){const dir=state.observer==='b'?-1:1;const before=state.t;state.t=clamp(state.t+raw/48*dir);const lived=Math.abs(state.t-before)*48;state.personalTime+=lived;if(dir>0)state.forwardMemory+=lived;else state.reverseMemory+=lived;if(state.t===0||state.t===1){state.playing=false;updateButtons();notify('시간 경계 · 처음부터 새 여정을 시작하세요');}}
 updateWorld();updateCamera(state.playing?dt:0,state.playing?raw:0);checkPortal();updateNeurons();if(frameCount%6===0)renderer.shadowMap.needsUpdate=true;postMat.uniforms.uTime.value=reduced?0:elapsed;postMat.uniforms.uReverse.value=mix(postMat.uniforms.uReverse.value,(state.entered&&state.observer==='b'&&state.playing)?1:0,dt*3);postMat.uniforms.uFade.value=Math.min(1,elapsed*.65);waterUniforms.uEye.value.copy(camera.position);
 if(audioCtx&&state.sound){windFilter.frequency.setTargetAtTime(350+state.t*550,audioCtx.currentTime,.1);if(elapsed>nextBird){birdsong();nextBird=elapsed+6+Math.random()*8;}}
 const signature=[state.t.toFixed(6),state.entered,state.observer,state.playing,state.inspected,camera.position.x.toFixed(4),camera.position.y.toFixed(4),camera.position.z.toFixed(4),camera.quaternion.x.toFixed(5),camera.quaternion.y.toFixed(5),camera.quaternion.z.toFixed(5),camera.quaternion.w.toFixed(5),innerWidth,innerHeight,renderer.getPixelRatio(),postMat.uniforms.uFade.value.toFixed(3)].join('|');
 if(signature===lastRenderSignature&&frameCount>3)return;lastRenderSignature=signature;
 draw();frameCount++;if(frameCount===3){$('#enter').disabled=false;$('#enter-label').textContent='들어가기';}
 // A sustained low frame rate reduces resolution once instead of sacrificing motion.
 if(raw>.065)slowFrames++;else slowFrames=Math.max(0,slowFrames-1);if(slowFrames>35&&renderer.getPixelRatio()>.8){renderer.setPixelRatio(.8);resize();slowFrames=-1000;}
}
renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();state.playing=false;$('#error').classList.add('show');});
updateButtons();updateWorld();animate();
// Read-only inspection for deterministic rendering tests, no controls or story text added.
window.__forest={snapshot:()=>({t:state.t,observer:state.observer,playing:state.playing,entered:state.entered,cinema:state.cinema,personalTime:state.personalTime,forwardMemory:state.forwardMemory,reverseMemory:state.reverseMemory,crossings:state.crossings,inspected:state.inspected,runnerMemory:runnerMemory(),runnerPhase:runnerPhase(),runnerPosition:runner.position.toArray(),runnerScreen:runnerScreen(),portalArmed:state.portalArmed,camera:camera.position.toArray(),memories:memories.filter(m=>m.material.emissiveIntensity>1).length,stone:blocks[6].mesh.position.toArray(),leaf:Array.from(fallingLeaves.instanceMatrix.array.slice(12,15)),drawCalls:sceneCounters.calls,triangles:sceneCounters.triangles,webgl2:renderer.capabilities.isWebGL2}),ready:true};
})();
